CREATE TABLE S (
	SNO char(2) NOT NULL,
	SNAME varchar(10) NOT NULL,
	STATUS int NOT NULL,
	CITY varchar(10) NOT NULL
);
ALTER TABLE S
ADD PRIMARY KEY (SNO);

CREATE TABLE P (
	PNO char(2) NOT NULL,
	PNAME varchar(10) NOT NULL,
	COLOR varchar(10),
	WEIGHT int NOT NULL,
	CITY varchar(10) NOT NULL
);
ALTER TABLE P
ADD PRIMARY KEY (PNO);

CREATE TABLE J (
	JNO char(2) NOT NULL,
	JNAME varchar(10) NOT NULL,
	CITY varchar(10) NOT NULL
);
ALTER TABLE J
ADD PRIMARY KEY (JNO);

CREATE TABLE SPJ (
	SNO char(2) NOT NULL,
	PNO char(2) NOT NULL,
	JNO char(2) NOT NULL,
	QTY int NOT NULL
);
